language: ruby
version: 1.9.3
before_script: 
  - mysql -e 'create database camilo_test;'
  - "sh -e /etc/init.d/xvfb start"
script: PADRINO_ENV=travis padrino rake
bundler_args: --without development production